/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "BleServiceStructure.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(McServerListResponse, McServerListResponse, AUTO)


PB_BIND(McMalfunctionRequest, McMalfunctionRequest, AUTO)


PB_BIND(McMalfunctionResponse, McMalfunctionResponse, AUTO)


PB_BIND(McMalfunctionResponse_ServerCodeStatus, McMalfunctionResponse_ServerCodeStatus, AUTO)


PB_BIND(McMalfunctionIntervalRequest, McMalfunctionIntervalRequest, AUTO)


PB_BIND(McVehicleIdentificationRequest, McVehicleIdentificationRequest, AUTO)


PB_BIND(McVehicleIdentificationResponse, McVehicleIdentificationResponse, AUTO)


PB_BIND(McVehicleIdentificationResponse_IdData, McVehicleIdentificationResponse_IdData, AUTO)


PB_BIND(McMarketDataRequest, McMarketDataRequest, AUTO)


PB_BIND(McMarketDataResponse, McMarketDataResponse, AUTO)


PB_BIND(McMarketDataResponse_IdData, McMarketDataResponse_IdData, AUTO)


PB_BIND(McLocalRecordVehicleInformationSupportIdListResponse, McLocalRecordVehicleInformationSupportIdListResponse, AUTO)


PB_BIND(McLocalRecordVehicleInformationRequest, McLocalRecordVehicleInformationRequest, AUTO)


PB_BIND(McLocalRecordVehicleInformationResponse, McLocalRecordVehicleInformationResponse, AUTO)


PB_BIND(McLocalRecordVehicleInformationResponse_IdData, McLocalRecordVehicleInformationResponse_IdData, AUTO)


PB_BIND(McLocalRecordVehicleInformationIntervalRequest, McLocalRecordVehicleInformationIntervalRequest, AUTO)


PB_BIND(McFfdResponse, McFfdResponse, AUTO)


PB_BIND(McCanResponse, McCanResponse, AUTO)


PB_BIND(McCanResponse_IdData, McCanResponse_IdData, AUTO)


PB_BIND(McNotificationDataV2, McNotificationDataV2, AUTO)






