EMWI_COLOR_FORMAT := RGBA8888
EMWI_SURFACE_ROTATION := 0
EMWIFILES := \
	Core.c \
	Effects.c \
	Graphics.c \
	Resources.c \
	Views.c \
	Application.c \
	WidgetSet.c \
	Templates.c \
	Components.c \
	UIConfig.c \
	Resource.c \
	Settings.c \
	Navigation.c \
	Menu.c \
	Media.c \
	Fonts.c \
	Effect.c \
	Enum.c \
	DeviceInterface.c \
	Factory.c \
	Development.c \
	Strings.c \
	Launcher.c \
	Home.c \
	Top.c \
	Weather.c \
	Pop.c