/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#include "dcd.h"

/* Component ID definition, used by tools. */
#ifndef FSL_COMPONENT_ID
#define FSL_COMPONENT_ID "platform.drivers.xip_board"
#endif

#if defined(XIP_BOOT_HEADER_ENABLE) && (XIP_BOOT_HEADER_ENABLE == 1)
#if defined(XIP_BOOT_HEADER_DCD_ENABLE) && (XIP_BOOT_HEADER_DCD_ENABLE == 1)
#if defined(__CC_ARM) || defined(__ARMCC_VERSION) || defined(__GNUC__)
__attribute__((section(".boot_hdr.dcd_data"), used))
#elif defined(__ICCARM__)
#pragma location = ".boot_hdr.dcd_data"
#endif

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: DCDx V2.0
processor: MIMXRT1172xxxxx
package_id: MIMXRT1172AVM8A
mcu_data: ksdk2_0
processor_version: 9.0.0
output_format: c_array
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* COMMENTS BELOW ARE USED AS SETTINGS FOR DCD DATA */
#if USE_XMCD
const uint32_t dcd_data[] = {
    /*
    Please check chapter 10.8 in RM_Rev_H
    0xC010000D: Tag = 0xC, Version = 0
                Memory Interface: SEMC
                Instance: 0 - ignored
                Configuration block type: 0 - Ignored
                (Handled inside the SDRAM configuration structure)
                Configuration block size: 13 (4-byte header + 9-byte option block)
    0xA60001A1: Magic_number = 0xA1
                Version = 1
                Config_option: Simplified
                SDRAM clock: 166MHz
    0x00004000: SDRAM CS0 size: 16MBytes
    0x01      : Port_size: 16-bit
    */
    0x0, 0x0, 0x0, 0x0, 0xC010000D, 0xA60001A1, 0x00004000, 0x01,
};
#else
const uint8_t dcd_data[] = {
	/* HEADER */
	/* Tag */
	0xD2,
	/* Image Length */
	0x00, 0x04,
	/* Version */
	0x41
	};
/* BE CAREFUL MODIFYING THIS SETTINGS - IT IS YAML SETTINGS FOR TOOLS */
#endif
#else
const uint8_t dcd_data[] = {0x00};
#endif /* XIP_BOOT_HEADER_DCD_ENABLE */
#endif /* XIP_BOOT_HEADER_ENABLE */
