/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176AVM8A
mcu_data: ksdk2_0
processor_version: 0.0.4
pin_labels:
- {pin_num: B15, pin_signal: GPIO_SD_B1_04, label: TFT_RESET, identifier: TFT_RESET}
- {pin_num: C15, pin_signal: GPIO_SD_B1_02, label: TFT_CONNECTED, identifier: TFT_CONNECTED}
- {pin_num: M17, pin_signal: GPIO_AD_29, label: TFT_BL_PWM, identifier: TFT_BL_PWM}
- {pin_num: D15, pin_signal: GPIO_SD_B1_01, label: TFT_ASIL, identifier: TFT_ASIL}
- {pin_num: L17, pin_signal: GPIO_AD_28, label: CAN_STBY, identifier: CAN_STBY}
- {pin_num: T17, pin_signal: GPIO_AD_07, label: VBATT_SENSE}
- {pin_num: R17, pin_signal: GPIO_AD_10, label: VDD_3.3V_PGOOD, identifier: VDD_3V3_PGOOD}
- {pin_num: P16, pin_signal: GPIO_AD_11, label: 5V_CAN_PGOOD, identifier: CAN_PGOOD}
- {pin_num: R16, pin_signal: GPIO_AD_09, label: VDD_3.3VON_PGOOD, identifier: VDD_3V3ON_PGOOD}
- {pin_num: M13, pin_signal: GPIO_AD_04, label: WDOG_B, identifier: WDOG_B}
- {pin_num: P6, pin_signal: GPIO_LPSR_02, label: BOOT_MODE0}
- {pin_num: T7, pin_signal: GPIO_LPSR_03, label: BOOT_MODE1}
- {pin_num: N16, pin_signal: GPIO_AD_27, label: 5V_CAN_EN, identifier: d;VDD5V_CAN_EN;CAN_EN}
- {pin_num: J14, pin_signal: GPIO_SD_B2_01, label: DEBUG_LED, identifier: DEBUG_LED}
- {pin_num: N12, pin_signal: GPIO_AD_00, label: BT_UART_TX}
- {pin_num: R14, pin_signal: GPIO_AD_01, label: BT_UART_RX}
- {pin_num: R13, pin_signal: GPIO_AD_02, label: BT_UART_CTS}
- {pin_num: P15, pin_signal: GPIO_AD_03, label: BT_UART_RTS}
- {pin_num: K17, pin_signal: GPIO_AD_30, label: CAN_TX}
- {pin_num: J17, pin_signal: GPIO_AD_31, label: CAN_RX}
- {pin_num: K16, pin_signal: GPIO_AD_32, label: EEPROM_I2C_SCL}
- {pin_num: H17, pin_signal: GPIO_AD_33, label: EEPROM_I2C_SDA}
- {pin_num: P8, pin_signal: GPIO_LPSR_06, label: DEBUG_UART_TX}
- {pin_num: R8, pin_signal: GPIO_LPSR_07, label: DEBUG_UART_RX}
- {pin_num: R5, pin_signal: GPIO_LPSR_10, label: JTAG_NRST}
- {pin_num: T5, pin_signal: GPIO_LPSR_11, label: JTAG_TDO/SWO}
- {pin_num: U5, pin_signal: GPIO_LPSR_12, label: JTAG_TDI}
- {pin_num: U6, pin_signal: GPIO_LPSR_13, label: JTAG_MOD}
- {pin_num: T6, pin_signal: GPIO_LPSR_14, label: JTAG_TCK_SWCLK}
- {pin_num: U7, pin_signal: GPIO_LPSR_15, label: JTAG_TMS_SWDIO}
- {pin_num: J15, pin_signal: GPIO_SD_B2_00, label: TFT_SPI_SCK}
- {pin_num: H13, pin_signal: GPIO_SD_B2_02, label: TFT_SPI_SISO}
- {pin_num: E14, pin_signal: GPIO_SD_B2_05, label: QSPI DQS}
- {pin_num: F17, pin_signal: GPIO_SD_B2_06, label: FLEXSPI_CS}
- {pin_num: G14, pin_signal: GPIO_SD_B2_07, label: FLEXSPI_SCK}
- {pin_num: F15, pin_signal: GPIO_SD_B2_08, label: FLEXSPI_D0}
- {pin_num: H15, pin_signal: GPIO_SD_B2_09, label: FLEXSPI_D1}
- {pin_num: H14, pin_signal: GPIO_SD_B2_10, label: FLEXSPI_D2}
- {pin_num: F16, pin_signal: GPIO_SD_B2_11, label: FLEXSPI_D3}
- {pin_num: U9, pin_signal: PMIC_ON_REQ, label: SYS_EN, identifier: SYS_EN}
- {pin_num: T9, pin_signal: PMIC_STBY_REQ, label: PMIC_STBY_REQ}
- {pin_num: T8, pin_signal: WAKEUP, label: IGN_WAKE, identifier: IGN_WAKE}
- {pin_num: E13, pin_signal: GPIO_DISP_B1_00, label: TFT_RGB_CLK}
- {pin_num: D13, pin_signal: GPIO_DISP_B1_01, label: TFT_RGB_DE, identifier: LCDIF_ENABLE}
- {pin_num: D11, pin_signal: GPIO_DISP_B1_02, label: TFT_RGB_HSYNC}
- {pin_num: E11, pin_signal: GPIO_DISP_B1_03, label: TFT_RGB_VSYNC}
- {pin_num: E10, pin_signal: GPIO_DISP_B1_04, label: TFT_RGB_B0}
- {pin_num: C11, pin_signal: GPIO_DISP_B1_05, label: TFT_RGB_B1}
- {pin_num: D10, pin_signal: GPIO_DISP_B1_06, label: TFT_RGB_B2}
- {pin_num: E12, pin_signal: GPIO_DISP_B1_07, label: TFT_RGB_B3}
- {pin_num: A15, pin_signal: GPIO_DISP_B1_08, label: TFT_RGB_B4}
- {pin_num: C13, pin_signal: GPIO_DISP_B1_09, label: TFT_RGB_B5}
- {pin_num: B14, pin_signal: GPIO_DISP_B1_10, label: TFT_RGB_B6}
- {pin_num: A14, pin_signal: GPIO_DISP_B1_11, label: TFT_RGB_B7}
- {pin_num: E8, pin_signal: GPIO_DISP_B2_00, label: TFT_RGB_G0}
- {pin_num: F8, pin_signal: GPIO_DISP_B2_01, label: TFT_RGB_G1}
- {pin_num: E9, pin_signal: GPIO_DISP_B2_02, label: TFT_RGB_G2}
- {pin_num: D7, pin_signal: GPIO_DISP_B2_03, label: TFT_RGB_G3}
- {pin_num: C7, pin_signal: GPIO_DISP_B2_04, label: TFT_RGB_G4}
- {pin_num: C9, pin_signal: GPIO_DISP_B2_05, label: TFT_RGB_G5}
- {pin_num: C6, pin_signal: GPIO_DISP_B2_06, label: TFT_RGB_G6}
- {pin_num: D6, pin_signal: GPIO_DISP_B2_07, label: TFT_RGB_G7}
- {pin_num: B5, pin_signal: GPIO_DISP_B2_08, label: TFT_RGB_R0}
- {pin_num: D8, pin_signal: GPIO_DISP_B2_09, label: TFT_RGB_R1}
- {pin_num: D9, pin_signal: GPIO_DISP_B2_10, label: TFT_RGB_R2}
- {pin_num: A6, pin_signal: GPIO_DISP_B2_11, label: TFT_RGB_R3}
- {pin_num: B6, pin_signal: GPIO_DISP_B2_12, label: TFT_RGB_R4}
- {pin_num: A5, pin_signal: GPIO_DISP_B2_13, label: TFT_RGB_R5}
- {pin_num: A7, pin_signal: GPIO_DISP_B2_14, label: TFT_RGB_R6}
- {pin_num: A4, pin_signal: GPIO_DISP_B2_15, label: TFT_RGB_R7}
- {pin_num: F3, pin_signal: GPIO_EMC_B1_00, label: SDRAM_SEMC_D0}
- {pin_num: F2, pin_signal: GPIO_EMC_B1_01, label: SDRAM_SEMC_D1}
- {pin_num: G4, pin_signal: GPIO_EMC_B1_02, label: SDRAM_SEMC_D2}
- {pin_num: E4, pin_signal: GPIO_EMC_B1_03, label: SDRAM_SEMC_D3}
- {pin_num: H5, pin_signal: GPIO_EMC_B1_04, label: SDRAM_SEMC_D4}
- {pin_num: F4, pin_signal: GPIO_EMC_B1_05, label: SDRAM_SEMC_D5}
- {pin_num: H4, pin_signal: GPIO_EMC_B1_06, label: SDRAM_SEMC_D6}
- {pin_num: H3, pin_signal: GPIO_EMC_B1_07, label: SDRAM_SEMC_D7}
- {pin_num: F5, pin_signal: GPIO_EMC_B1_08, label: SDRAM_SEMC_DQML}
- {pin_num: A3, pin_signal: GPIO_EMC_B1_09, label: SDRAM_SEMC_A0}
- {pin_num: A2, pin_signal: GPIO_EMC_B1_10, label: SDRAM_SEMC_A1}
- {pin_num: C2, pin_signal: GPIO_EMC_B1_11, label: SDRAM_SEMC_A2}
- {pin_num: C5, pin_signal: GPIO_EMC_B1_12, label: SDRAM_SEMC_A3}
- {pin_num: D5, pin_signal: GPIO_EMC_B1_13, label: SDRAM_SEMC_A4}
- {pin_num: B1, pin_signal: GPIO_EMC_B1_14, label: SDRAM_SEMC_A5}
- {pin_num: C1, pin_signal: GPIO_EMC_B1_15, label: SDRAM_SEMC_A6}
- {pin_num: D3, pin_signal: GPIO_EMC_B1_16, label: SDRAM_SEMC_A7}
- {pin_num: B3, pin_signal: GPIO_EMC_B1_17, label: SDRAM_SEMC_A8}
- {pin_num: B4, pin_signal: GPIO_EMC_B1_18, label: SDRAM_SEMC_A9}
- {pin_num: C4, pin_signal: GPIO_EMC_B1_19, label: SDRAM_SEMC_A11}
- {pin_num: G2, pin_signal: GPIO_EMC_B1_21, label: SDRAM_SEMC_BA0}
- {pin_num: H2, pin_signal: GPIO_EMC_B1_22, label: SDRAM_SEMC_BA1}
- {pin_num: B2, pin_signal: GPIO_EMC_B1_23, label: SDRAM_SEMC_A10}
- {pin_num: J5, pin_signal: GPIO_EMC_B1_24, label: SDRAM_SEMC_CAS}
- {pin_num: J4, pin_signal: GPIO_EMC_B1_25, label: SDRAM_SEMC_RAS}
- {pin_num: J3, pin_signal: GPIO_EMC_B1_26, label: SDRAM_SEMC_CLK}
- {pin_num: G5, pin_signal: GPIO_EMC_B1_27, label: SDRAM_SEMC_CKE}
- {pin_num: E5, pin_signal: GPIO_EMC_B1_28, label: SDRAM_SEMC_WE}
- {pin_num: E6, pin_signal: GPIO_EMC_B1_29, label: SDRAM_SEMC_CS0}
- {pin_num: E3, pin_signal: GPIO_EMC_B1_30, label: SDRAM_SEMC_D8}
- {pin_num: D2, pin_signal: GPIO_EMC_B1_31, label: SDRAM_SEMC_D9}
- {pin_num: E2, pin_signal: GPIO_EMC_B1_33, label: SDRAM_SEMC_D11}
- {pin_num: E1, pin_signal: GPIO_EMC_B1_34, label: SDRAM_SEMC_D12}
- {pin_num: F1, pin_signal: GPIO_EMC_B1_35, label: SDRAM_SEMC_D13}
- {pin_num: G1, pin_signal: GPIO_EMC_B1_36, label: SDRAM_SEMC_D14}
- {pin_num: H1, pin_signal: GPIO_EMC_B1_37, label: SDRAM_SEMC_D15}
- {pin_num: J1, pin_signal: GPIO_EMC_B1_38, label: SDRAM_SEMC_DQMH}
- {pin_num: D1, pin_signal: GPIO_EMC_B1_32, label: SDRAM_SEMC_D10}
- {pin_num: R1, pin_signal: GPIO_EMC_B2_03, label: HW_ID0, identifier: HW_ID0}
- {pin_num: P1, pin_signal: GPIO_EMC_B2_08, label: HW_ID3, identifier: HW_ID3}
- {pin_num: N1, pin_signal: GPIO_EMC_B2_05, label: HW_ID2, identifier: HW_ID2}
- {pin_num: M1, pin_signal: GPIO_EMC_B2_04, label: HW_ID1, identifier: HW_ID1}
- {pin_num: R2, pin_signal: GPIO_EMC_B2_10, label: SKU_ID1, identifier: SKU_ID1}
- {pin_num: P2, pin_signal: GPIO_EMC_B2_16, label: SKU_ID3, identifier: SKU_ID3}
- {pin_num: N2, pin_signal: GPIO_EMC_B2_09, label: SKU_ID0, identifier: SKU_ID0}
- {pin_num: M2, pin_signal: GPIO_EMC_B2_12, label: SKU_ID2, identifier: SKU_ID2}
- {pin_num: N17, pin_signal: GPIO_AD_16, label: TFT_TEMPERATURE}
- {pin_num: P17, pin_signal: GPIO_AD_12, label: PCBA_TEMPERATURE}
- {pin_num: P13, pin_signal: GPIO_AD_05, label: BT_WAKE_HOST}
- {pin_num: R15, pin_signal: GPIO_AD_08, label: BT_RST_N, identifier: BT_RST_N}
- {pin_num: F14, pin_signal: GPIO_SD_B2_04, label: TFT_SPI_CSB}
- {pin_num: B16, pin_signal: GPIO_SD_B1_00, label: TFT_BL_EN, identifier: TFT_BL_EN}
- {pin_num: B17, pin_signal: GPIO_SD_B1_03, label: TFT_RESET, identifier: TFT_RESET}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitLcdifPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: P8, peripheral: LPUART12, signal: TXD, pin_signal: GPIO_LPSR_06}
  - {pin_num: R8, peripheral: LPUART12, signal: RXD, pin_signal: GPIO_LPSR_07}
  - {pin_num: J15, peripheral: LPSPI4, signal: SCK, pin_signal: GPIO_SD_B2_00}
  - {pin_num: K16, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_AD_32, software_input_on: Enable, pull_up_down_config: Pull_Up, pull_keeper_select: Keeper, open_drain: Enable}
  - {pin_num: H17, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_AD_33, software_input_on: Enable, pull_up_down_config: Pull_Up, pull_keeper_select: Keeper, open_drain: Enable}
  - {pin_num: K17, peripheral: CAN2, signal: TX, pin_signal: GPIO_AD_30, pull_up_down_config: Pull_Down, pull_keeper_select: Pull}
  - {pin_num: J17, peripheral: CAN2, signal: RX, pin_signal: GPIO_AD_31, pull_up_down_config: Pull_Up, pull_keeper_select: Pull}
  - {pin_num: H13, peripheral: LPSPI4, signal: SOUT, pin_signal: GPIO_SD_B2_02}
  - {pin_num: R13, peripheral: LPUART7, signal: CTS_B, pin_signal: GPIO_AD_02}
  - {pin_num: P15, peripheral: LPUART7, signal: RTS_B, pin_signal: GPIO_AD_03}
  - {pin_num: R14, peripheral: LPUART7, signal: RXD, pin_signal: GPIO_AD_01, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper}
  - {pin_num: N12, peripheral: LPUART7, signal: TXD, pin_signal: GPIO_AD_00, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper, drive_strength: Normal}
  - {pin_num: C15, peripheral: GPIO10, signal: 'gpio_io, 05', pin_signal: GPIO_SD_B1_02, direction: INPUT}
  - {pin_num: D15, peripheral: GPIO10, signal: 'gpio_io, 04', pin_signal: GPIO_SD_B1_01, direction: INPUT}
  - {pin_num: T8, peripheral: GPIO13, signal: 'gpio_io, 00', pin_signal: WAKEUP, direction: INPUT, gpio_interrupt: kGPIO_IntFallingEdge}
  - {pin_num: T9, peripheral: GPIO13, signal: 'gpio_io, 02', pin_signal: PMIC_STBY_REQ}
  - {pin_num: T17, peripheral: ADC1, signal: 'B, 1_0', pin_signal: GPIO_AD_07, pull_keeper_select: Keeper}
  - {pin_num: R17, peripheral: GPIO9, signal: 'gpio_io, 09', pin_signal: GPIO_AD_10, direction: INPUT}
  - {pin_num: R16, peripheral: GPIO9, signal: 'gpio_io, 08', pin_signal: GPIO_AD_09, direction: INPUT}
  - {pin_num: P16, peripheral: GPIO9, signal: 'gpio_io, 10', pin_signal: GPIO_AD_11, direction: INPUT}
  - {pin_num: N16, peripheral: GPIO9, signal: 'gpio_io, 26', pin_signal: GPIO_AD_27, identifier: CAN_EN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: J14, peripheral: GPIO10, signal: 'gpio_io, 10', pin_signal: GPIO_SD_B2_01, direction: OUTPUT}
  - {pin_num: L17, peripheral: GPIO9, signal: 'gpio_io, 27', pin_signal: GPIO_AD_28, direction: OUTPUT}
  - {pin_num: F14, peripheral: LPSPI4, signal: PCS1, pin_signal: GPIO_SD_B2_04}
  - {pin_num: M1, peripheral: GPIO8, signal: 'gpio_io, 14', pin_signal: GPIO_EMC_B2_04, direction: INPUT}
  - {pin_num: N1, peripheral: GPIO8, signal: 'gpio_io, 15', pin_signal: GPIO_EMC_B2_05, direction: INPUT}
  - {pin_num: P1, peripheral: GPIO8, signal: 'gpio_io, 18', pin_signal: GPIO_EMC_B2_08, direction: INPUT}
  - {pin_num: R1, peripheral: GPIO8, signal: 'gpio_io, 13', pin_signal: GPIO_EMC_B2_03, direction: INPUT}
  - {pin_num: M2, peripheral: GPIO8, signal: 'gpio_io, 22', pin_signal: GPIO_EMC_B2_12, direction: INPUT}
  - {pin_num: N2, peripheral: GPIO8, signal: 'gpio_io, 19', pin_signal: GPIO_EMC_B2_09, direction: INPUT}
  - {pin_num: P2, peripheral: GPIO8, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_B2_16, direction: INPUT}
  - {pin_num: R2, peripheral: GPIO8, signal: 'gpio_io, 20', pin_signal: GPIO_EMC_B2_10, direction: INPUT}
  - {pin_num: N17, peripheral: ADC1, signal: 'A, 1_5', pin_signal: GPIO_AD_16, pull_keeper_select: Keeper}
  - {pin_num: P17, peripheral: ADC1, signal: 'A, 1_3', pin_signal: GPIO_AD_12, pull_keeper_select: Keeper}
  - {pin_num: R15, peripheral: GPIO9, signal: 'gpio_io, 07', pin_signal: GPIO_AD_08, direction: OUTPUT, gpio_init_state: 'true', pull_up_down_config: Pull_Up}
  - {pin_num: P13, peripheral: GPIO9, signal: 'gpio_io, 04', pin_signal: GPIO_AD_05}
  - {pin_num: B17, peripheral: GPIO10, signal: 'gpio_io, 06', pin_signal: GPIO_SD_B1_03, direction: OUTPUT}
  - {pin_num: B1, peripheral: SEMC, signal: 'ADDR, 05', pin_signal: GPIO_EMC_B1_14}
  - {pin_num: K1, peripheral: SEMC, signal: semc_rdy, pin_signal: GPIO_EMC_B1_40}
  - {pin_num: L1, peripheral: SEMC, signal: 'CSX, 0', pin_signal: GPIO_EMC_B1_41}
  - {pin_num: C1, peripheral: SEMC, signal: 'ADDR, 06', pin_signal: GPIO_EMC_B1_15}
  - {pin_num: D1, peripheral: SEMC, signal: 'DATA, 10', pin_signal: GPIO_EMC_B1_32}
  - {pin_num: E1, peripheral: SEMC, signal: 'DATA, 12', pin_signal: GPIO_EMC_B1_34}
  - {pin_num: F1, peripheral: SEMC, signal: 'DATA, 13', pin_signal: GPIO_EMC_B1_35}
  - {pin_num: G1, peripheral: SEMC, signal: 'DATA, 14', pin_signal: GPIO_EMC_B1_36}
  - {pin_num: H1, peripheral: SEMC, signal: 'DATA, 15', pin_signal: GPIO_EMC_B1_37}
  - {pin_num: J1, peripheral: SEMC, signal: 'DM, 1', pin_signal: GPIO_EMC_B1_38}
  - {pin_num: A2, peripheral: SEMC, signal: 'ADDR, 01', pin_signal: GPIO_EMC_B1_10}
  - {pin_num: B2, peripheral: SEMC, signal: 'ADDR, 10', pin_signal: GPIO_EMC_B1_23}
  - {pin_num: C2, peripheral: SEMC, signal: 'ADDR, 02', pin_signal: GPIO_EMC_B1_11}
  - {pin_num: D2, peripheral: SEMC, signal: 'DATA, 09', pin_signal: GPIO_EMC_B1_31}
  - {pin_num: F2, peripheral: SEMC, signal: 'DATA, 01', pin_signal: GPIO_EMC_B1_01}
  - {pin_num: E2, peripheral: SEMC, signal: 'DATA, 11', pin_signal: GPIO_EMC_B1_33}
  - {pin_num: G2, peripheral: SEMC, signal: 'BA, 0', pin_signal: GPIO_EMC_B1_21}
  - {pin_num: H2, peripheral: SEMC, signal: 'BA, 1', pin_signal: GPIO_EMC_B1_22}
  - {pin_num: A3, peripheral: SEMC, signal: 'ADDR, 00', pin_signal: GPIO_EMC_B1_09}
  - {pin_num: B3, peripheral: SEMC, signal: 'ADDR, 08', pin_signal: GPIO_EMC_B1_17}
  - {pin_num: C3, peripheral: SEMC, signal: 'ADDR, 12', pin_signal: GPIO_EMC_B1_20}
  - {pin_num: D3, peripheral: SEMC, signal: 'ADDR, 07', pin_signal: GPIO_EMC_B1_16}
  - {pin_num: E3, peripheral: SEMC, signal: 'DATA, 08', pin_signal: GPIO_EMC_B1_30}
  - {pin_num: F3, peripheral: SEMC, signal: 'DATA, 00', pin_signal: GPIO_EMC_B1_00}
  - {pin_num: H3, peripheral: SEMC, signal: 'DATA, 07', pin_signal: GPIO_EMC_B1_07}
  - {pin_num: J3, peripheral: SEMC, signal: semc_clk, pin_signal: GPIO_EMC_B1_26}
  - {pin_num: B4, peripheral: SEMC, signal: 'ADDR, 09', pin_signal: GPIO_EMC_B1_18}
  - {pin_num: C4, peripheral: SEMC, signal: 'ADDR, 11', pin_signal: GPIO_EMC_B1_19}
  - {pin_num: F4, peripheral: SEMC, signal: 'DATA, 05', pin_signal: GPIO_EMC_B1_05}
  - {pin_num: G4, peripheral: SEMC, signal: 'DATA, 02', pin_signal: GPIO_EMC_B1_02}
  - {pin_num: E4, peripheral: SEMC, signal: 'DATA, 03', pin_signal: GPIO_EMC_B1_03}
  - {pin_num: H4, peripheral: SEMC, signal: 'DATA, 06', pin_signal: GPIO_EMC_B1_06}
  - {pin_num: J4, peripheral: SEMC, signal: semc_ras, pin_signal: GPIO_EMC_B1_25}
  - {pin_num: C5, peripheral: SEMC, signal: 'ADDR, 03', pin_signal: GPIO_EMC_B1_12}
  - {pin_num: D5, peripheral: SEMC, signal: 'ADDR, 04', pin_signal: GPIO_EMC_B1_13}
  - {pin_num: E5, peripheral: SEMC, signal: semc_we, pin_signal: GPIO_EMC_B1_28}
  - {pin_num: F5, peripheral: SEMC, signal: 'DM, 0', pin_signal: GPIO_EMC_B1_08}
  - {pin_num: G5, peripheral: SEMC, signal: semc_cke, pin_signal: GPIO_EMC_B1_27}
  - {pin_num: H5, peripheral: SEMC, signal: 'DATA, 04', pin_signal: GPIO_EMC_B1_04}
  - {pin_num: J5, peripheral: SEMC, signal: semc_cas, pin_signal: GPIO_EMC_B1_24}
  - {pin_num: E6, peripheral: SEMC, signal: 'CS, 0', pin_signal: GPIO_EMC_B1_29}
  - {pin_num: T7, peripheral: SRC, signal: 'BOOT_MODE, 01', pin_signal: GPIO_LPSR_03}
  - {pin_num: P6, peripheral: SRC, signal: 'BOOT_MODE, 00', pin_signal: GPIO_LPSR_02}
  - {pin_num: M17, peripheral: FLEXIO2, signal: 'IO, 29', pin_signal: GPIO_AD_29, direction: OUTPUT}
  - {pin_num: B16, peripheral: GPIO10, signal: 'gpio_io, 03', pin_signal: GPIO_SD_B1_00, direction: OUTPUT}
  - {pin_num: M13, peripheral: GPIO9, signal: 'gpio_io, 03', pin_signal: GPIO_AD_04, direction: OUTPUT}
  - {pin_num: U9, peripheral: SNVS, signal: snvs_lp_pmic_on_req, pin_signal: PMIC_ON_REQ, identifier: ''}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  /* GPIO configuration of HW_ID0 on GPIO_EMC_B2_03 (pin R1) */
  gpio_pin_config_t HW_ID0_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_03 (pin R1) */
  GPIO_PinInit(GPIO8, 13U, &HW_ID0_config);

  /* GPIO configuration of HW_ID1 on GPIO_EMC_B2_04 (pin M1) */
  gpio_pin_config_t HW_ID1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_04 (pin M1) */
  GPIO_PinInit(GPIO8, 14U, &HW_ID1_config);

  /* GPIO configuration of HW_ID2 on GPIO_EMC_B2_05 (pin N1) */
  gpio_pin_config_t HW_ID2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_05 (pin N1) */
  GPIO_PinInit(GPIO8, 15U, &HW_ID2_config);

  /* GPIO configuration of HW_ID3 on GPIO_EMC_B2_08 (pin P1) */
  gpio_pin_config_t HW_ID3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_08 (pin P1) */
  GPIO_PinInit(GPIO8, 18U, &HW_ID3_config);

  /* GPIO configuration of SKU_ID0 on GPIO_EMC_B2_09 (pin N2) */
  gpio_pin_config_t SKU_ID0_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_09 (pin N2) */
  GPIO_PinInit(GPIO8, 19U, &SKU_ID0_config);

  /* GPIO configuration of SKU_ID1 on GPIO_EMC_B2_10 (pin R2) */
  gpio_pin_config_t SKU_ID1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_10 (pin R2) */
  GPIO_PinInit(GPIO8, 20U, &SKU_ID1_config);

  /* GPIO configuration of SKU_ID2 on GPIO_EMC_B2_12 (pin M2) */
  gpio_pin_config_t SKU_ID2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_12 (pin M2) */
  GPIO_PinInit(GPIO8, 22U, &SKU_ID2_config);

  /* GPIO configuration of SKU_ID3 on GPIO_EMC_B2_16 (pin P2) */
  gpio_pin_config_t SKU_ID3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_16 (pin P2) */
  GPIO_PinInit(GPIO8, 26U, &SKU_ID3_config);

  /* GPIO configuration of WDOG_B on GPIO_AD_04 (pin M13) */
  gpio_pin_config_t WDOG_B_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_04 (pin M13) */
  GPIO_PinInit(GPIO9, 3U, &WDOG_B_config);

  /* GPIO configuration of BT_RST_N on GPIO_AD_08 (pin R15) */
  gpio_pin_config_t BT_RST_N_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_08 (pin R15) */
  GPIO_PinInit(GPIO9, 7U, &BT_RST_N_config);

  /* GPIO configuration of VDD_3V3ON_PGOOD on GPIO_AD_09 (pin R16) */
  gpio_pin_config_t VDD_3V3ON_PGOOD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_09 (pin R16) */
  GPIO_PinInit(GPIO9, 8U, &VDD_3V3ON_PGOOD_config);

  /* GPIO configuration of VDD_3V3_PGOOD on GPIO_AD_10 (pin R17) */
  gpio_pin_config_t VDD_3V3_PGOOD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_10 (pin R17) */
  GPIO_PinInit(GPIO9, 9U, &VDD_3V3_PGOOD_config);

  /* GPIO configuration of CAN_PGOOD on GPIO_AD_11 (pin P16) */
  gpio_pin_config_t CAN_PGOOD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_11 (pin P16) */
  GPIO_PinInit(GPIO9, 10U, &CAN_PGOOD_config);

  /* GPIO configuration of CAN_EN on GPIO_AD_27 (pin N16) */
  gpio_pin_config_t CAN_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_27 (pin N16) */
  GPIO_PinInit(GPIO9, 26U, &CAN_EN_config);

  /* GPIO configuration of CAN_STBY on GPIO_AD_28 (pin L17) */
  gpio_pin_config_t CAN_STBY_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_28 (pin L17) */
  GPIO_PinInit(GPIO9, 27U, &CAN_STBY_config);

  /* GPIO configuration of TFT_BL_EN on GPIO_SD_B1_00 (pin B16) */
  gpio_pin_config_t TFT_BL_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_00 (pin B16) */
  GPIO_PinInit(GPIO10, 3U, &TFT_BL_EN_config);

  /* GPIO configuration of TFT_ASIL on GPIO_SD_B1_01 (pin D15) */
  gpio_pin_config_t TFT_ASIL_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_01 (pin D15) */
  GPIO_PinInit(GPIO10, 4U, &TFT_ASIL_config);

  /* GPIO configuration of TFT_CONNECTED on GPIO_SD_B1_02 (pin C15) */
  gpio_pin_config_t TFT_CONNECTED_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_02 (pin C15) */
  GPIO_PinInit(GPIO10, 5U, &TFT_CONNECTED_config);

  /* GPIO configuration of TFT_RESET on GPIO_SD_B1_03 (pin B17) */
  gpio_pin_config_t TFT_RESET_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_03 (pin B17) */
  GPIO_PinInit(GPIO10, 6U, &TFT_RESET_config);

  /* GPIO configuration of DEBUG_LED on GPIO_SD_B2_01 (pin J14) */
  gpio_pin_config_t DEBUG_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B2_01 (pin J14) */
  GPIO_PinInit(GPIO10, 10U, &DEBUG_LED_config);

  /* GPIO configuration of IGN_WAKE on WAKEUP_DIG (pin T8) */
  gpio_pin_config_t IGN_WAKE_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntFallingEdge
  };
  /* Initialize GPIO functionality on WAKEUP_DIG (pin T8) */
  GPIO_PinInit(GPIO13, 0U, &IGN_WAKE_config);
  /* Enable GPIO pin interrupt on WAKEUP_DIG (pin T8) */
  GPIO_PortEnableInterrupts(GPIO13, 1U << 0U);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_00_LPUART7_TXD,          /* GPIO_AD_00 is configured as LPUART7_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_01_LPUART7_RXD,          /* GPIO_AD_01 is configured as LPUART7_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_02_LPUART7_CTS_B,        /* GPIO_AD_02 is configured as LPUART7_CTS_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_03_LPUART7_RTS_B,        /* GPIO_AD_03 is configured as LPUART7_RTS_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_04_GPIO9_IO03,           /* GPIO_AD_04 is configured as GPIO9_IO03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_05_GPIO9_IO04,           /* GPIO_AD_05 is configured as GPIO9_IO04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_07_GPIO_MUX3_IO06,       /* GPIO_AD_07 is configured as GPIO_MUX3_IO06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_08 is configured as GPIO9_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_09_GPIO9_IO08,           /* GPIO_AD_09 is configured as GPIO9_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_10_GPIO9_IO09,           /* GPIO_AD_10 is configured as GPIO9_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_11_GPIO9_IO10,           /* GPIO_AD_11 is configured as GPIO9_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_12_GPIO_MUX3_IO11,       /* GPIO_AD_12 is configured as GPIO_MUX3_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_16_GPIO_MUX3_IO15,       /* GPIO_AD_16 is configured as GPIO_MUX3_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_27_GPIO9_IO26,           /* GPIO_AD_27 is configured as GPIO9_IO26 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_28_GPIO9_IO27,           /* GPIO_AD_28 is configured as GPIO9_IO27 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_29_FLEXIO2_D29,          /* GPIO_AD_29 is configured as FLEXIO2_D29 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_30_FLEXCAN2_TX,          /* GPIO_AD_30 is configured as FLEXCAN2_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_31_FLEXCAN2_RX,          /* GPIO_AD_31 is configured as FLEXCAN2_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_32_LPI2C1_SCL,           /* GPIO_AD_32 is configured as LPI2C1_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_32 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_33_LPI2C1_SDA,           /* GPIO_AD_33 is configured as LPI2C1_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_33 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_00_SEMC_DATA00,      /* GPIO_EMC_B1_00 is configured as SEMC_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_01_SEMC_DATA01,      /* GPIO_EMC_B1_01 is configured as SEMC_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_02_SEMC_DATA02,      /* GPIO_EMC_B1_02 is configured as SEMC_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_03_SEMC_DATA03,      /* GPIO_EMC_B1_03 is configured as SEMC_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_04_SEMC_DATA04,      /* GPIO_EMC_B1_04 is configured as SEMC_DATA04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_05_SEMC_DATA05,      /* GPIO_EMC_B1_05 is configured as SEMC_DATA05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_06_SEMC_DATA06,      /* GPIO_EMC_B1_06 is configured as SEMC_DATA06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_07_SEMC_DATA07,      /* GPIO_EMC_B1_07 is configured as SEMC_DATA07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_08_SEMC_DM00,        /* GPIO_EMC_B1_08 is configured as SEMC_DM00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_09_SEMC_ADDR00,      /* GPIO_EMC_B1_09 is configured as SEMC_ADDR00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_10_SEMC_ADDR01,      /* GPIO_EMC_B1_10 is configured as SEMC_ADDR01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_11_SEMC_ADDR02,      /* GPIO_EMC_B1_11 is configured as SEMC_ADDR02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_12_SEMC_ADDR03,      /* GPIO_EMC_B1_12 is configured as SEMC_ADDR03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_13_SEMC_ADDR04,      /* GPIO_EMC_B1_13 is configured as SEMC_ADDR04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_14_SEMC_ADDR05,      /* GPIO_EMC_B1_14 is configured as SEMC_ADDR05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_15_SEMC_ADDR06,      /* GPIO_EMC_B1_15 is configured as SEMC_ADDR06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_16_SEMC_ADDR07,      /* GPIO_EMC_B1_16 is configured as SEMC_ADDR07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_17_SEMC_ADDR08,      /* GPIO_EMC_B1_17 is configured as SEMC_ADDR08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_18_SEMC_ADDR09,      /* GPIO_EMC_B1_18 is configured as SEMC_ADDR09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_19_SEMC_ADDR11,      /* GPIO_EMC_B1_19 is configured as SEMC_ADDR11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_20_SEMC_ADDR12,      /* GPIO_EMC_B1_20 is configured as SEMC_ADDR12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_21_SEMC_BA0,         /* GPIO_EMC_B1_21 is configured as SEMC_BA0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_22_SEMC_BA1,         /* GPIO_EMC_B1_22 is configured as SEMC_BA1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_23_SEMC_ADDR10,      /* GPIO_EMC_B1_23 is configured as SEMC_ADDR10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_24_SEMC_CAS,         /* GPIO_EMC_B1_24 is configured as SEMC_CAS */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_25_SEMC_RAS,         /* GPIO_EMC_B1_25 is configured as SEMC_RAS */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_26_SEMC_CLK,         /* GPIO_EMC_B1_26 is configured as SEMC_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_27_SEMC_CKE,         /* GPIO_EMC_B1_27 is configured as SEMC_CKE */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_28_SEMC_WE,          /* GPIO_EMC_B1_28 is configured as SEMC_WE */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_29_SEMC_CS0,         /* GPIO_EMC_B1_29 is configured as SEMC_CS0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_30_SEMC_DATA08,      /* GPIO_EMC_B1_30 is configured as SEMC_DATA08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_31_SEMC_DATA09,      /* GPIO_EMC_B1_31 is configured as SEMC_DATA09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_32_SEMC_DATA10,      /* GPIO_EMC_B1_32 is configured as SEMC_DATA10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_33_SEMC_DATA11,      /* GPIO_EMC_B1_33 is configured as SEMC_DATA11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_34_SEMC_DATA12,      /* GPIO_EMC_B1_34 is configured as SEMC_DATA12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_35_SEMC_DATA13,      /* GPIO_EMC_B1_35 is configured as SEMC_DATA13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_36_SEMC_DATA14,      /* GPIO_EMC_B1_36 is configured as SEMC_DATA14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_37_SEMC_DATA15,      /* GPIO_EMC_B1_37 is configured as SEMC_DATA15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_38_SEMC_DM01,        /* GPIO_EMC_B1_38 is configured as SEMC_DM01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_40_SEMC_RDY,         /* GPIO_EMC_B1_40 is configured as SEMC_RDY */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_41_SEMC_CSX00,       /* GPIO_EMC_B1_41 is configured as SEMC_CSX00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_03_GPIO8_IO13,       /* GPIO_EMC_B2_03 is configured as GPIO8_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_04_GPIO8_IO14,       /* GPIO_EMC_B2_04 is configured as GPIO8_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_05_GPIO8_IO15,       /* GPIO_EMC_B2_05 is configured as GPIO8_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_08_GPIO8_IO18,       /* GPIO_EMC_B2_08 is configured as GPIO8_IO18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_09_GPIO8_IO19,       /* GPIO_EMC_B2_09 is configured as GPIO8_IO19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_10_GPIO8_IO20,       /* GPIO_EMC_B2_10 is configured as GPIO8_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_12_GPIO8_IO22,       /* GPIO_EMC_B2_12 is configured as GPIO8_IO22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_16_GPIO8_IO26,       /* GPIO_EMC_B2_16 is configured as GPIO8_IO26 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_00_GPIO10_IO03,       /* GPIO_SD_B1_00 is configured as GPIO10_IO03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_01_GPIO10_IO04,       /* GPIO_SD_B1_01 is configured as GPIO10_IO04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_02_GPIO10_IO05,       /* GPIO_SD_B1_02 is configured as GPIO10_IO05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_03_GPIO10_IO06,       /* GPIO_SD_B1_03 is configured as GPIO10_IO06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_00_LPSPI4_SCK,        /* GPIO_SD_B2_00 is configured as LPSPI4_SCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_01_GPIO10_IO10,       /* GPIO_SD_B2_01 is configured as GPIO10_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_02_LPSPI4_SOUT,       /* GPIO_SD_B2_02 is configured as LPSPI4_SOUT */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_04_LPSPI4_PCS1,       /* GPIO_SD_B2_04 is configured as LPSPI4_PCS1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_02_SRC_BOOT_MODE00,    /* GPIO_LPSR_02 is configured as SRC_BOOT_MODE00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_03_SRC_BOOT_MODE01,    /* GPIO_LPSR_03 is configured as SRC_BOOT_MODE01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_06_LPUART12_TXD,       /* GPIO_LPSR_06 is configured as LPUART12_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_07_LPUART12_RXD,       /* GPIO_LPSR_07 is configured as LPUART12_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_PMIC_ON_REQ_DIG_SNVS_LP_PMIC_ON_REQ,  /* PMIC_ON_REQ_DIG is configured as SNVS_LP_PMIC_ON_REQ */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_PMIC_STBY_REQ_DIG_GPIO13_IO02,   /* PMIC_STBY_REQ_DIG is configured as GPIO13_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_WAKEUP_DIG_GPIO13_IO00,          /* WAKEUP_DIG is configured as GPIO13_IO00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_00_LPUART7_TXD,          /* GPIO_AD_00 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_01_LPUART7_RXD,          /* GPIO_AD_01 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_07_GPIO_MUX3_IO06,       /* GPIO_AD_07 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_08 PAD functional properties : */
      0x0EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_12_GPIO_MUX3_IO11,       /* GPIO_AD_12 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_16_GPIO_MUX3_IO15,       /* GPIO_AD_16 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_30_FLEXCAN2_TX,          /* GPIO_AD_30 PAD functional properties : */
      0x06U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_31_FLEXCAN2_RX,          /* GPIO_AD_31 PAD functional properties : */
      0x0EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_32_LPI2C1_SCL,           /* GPIO_AD_32 PAD functional properties : */
      0x1AU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_33_LPI2C1_SDA,           /* GPIO_AD_33 PAD functional properties : */
      0x1AU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Enabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLcdifPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: E13, peripheral: LCDIF, signal: lcdif_clk, pin_signal: GPIO_DISP_B1_00, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: E10, peripheral: LCDIF, signal: 'lcdif_data, 00', pin_signal: GPIO_DISP_B1_04, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: C11, peripheral: LCDIF, signal: 'lcdif_data, 01', pin_signal: GPIO_DISP_B1_05, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: D10, peripheral: LCDIF, signal: 'lcdif_data, 02', pin_signal: GPIO_DISP_B1_06, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: E12, peripheral: LCDIF, signal: 'lcdif_data, 03', pin_signal: GPIO_DISP_B1_07, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: A15, peripheral: LCDIF, signal: 'lcdif_data, 04', pin_signal: GPIO_DISP_B1_08, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: C13, peripheral: LCDIF, signal: 'lcdif_data, 05', pin_signal: GPIO_DISP_B1_09, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: B14, peripheral: LCDIF, signal: 'lcdif_data, 06', pin_signal: GPIO_DISP_B1_10, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: A14, peripheral: LCDIF, signal: 'lcdif_data, 07', pin_signal: GPIO_DISP_B1_11, pull_down_pull_up_config: Pull_Up, pdrv_config: Normal_Driver}
  - {pin_num: E8, peripheral: LCDIF, signal: 'lcdif_data, 08', pin_signal: GPIO_DISP_B2_00, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: F8, peripheral: LCDIF, signal: 'lcdif_data, 09', pin_signal: GPIO_DISP_B2_01, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: E9, peripheral: LCDIF, signal: 'lcdif_data, 10', pin_signal: GPIO_DISP_B2_02, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: D7, peripheral: LCDIF, signal: 'lcdif_data, 11', pin_signal: GPIO_DISP_B2_03, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: C7, peripheral: LCDIF, signal: 'lcdif_data, 12', pin_signal: GPIO_DISP_B2_04, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: C9, peripheral: LCDIF, signal: 'lcdif_data, 13', pin_signal: GPIO_DISP_B2_05, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: C6, peripheral: LCDIF, signal: 'lcdif_data, 14', pin_signal: GPIO_DISP_B2_06, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: D6, peripheral: LCDIF, signal: 'lcdif_data, 15', pin_signal: GPIO_DISP_B2_07, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: B5, peripheral: LCDIF, signal: 'lcdif_data, 16', pin_signal: GPIO_DISP_B2_08, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: D8, peripheral: LCDIF, signal: 'lcdif_data, 17', pin_signal: GPIO_DISP_B2_09, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: D9, peripheral: LCDIF, signal: 'lcdif_data, 18', pin_signal: GPIO_DISP_B2_10, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: A6, peripheral: LCDIF, signal: 'lcdif_data, 19', pin_signal: GPIO_DISP_B2_11, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: B6, peripheral: LCDIF, signal: 'lcdif_data, 20', pin_signal: GPIO_DISP_B2_12, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: A5, peripheral: LCDIF, signal: 'lcdif_data, 21', pin_signal: GPIO_DISP_B2_13, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: A7, peripheral: LCDIF, signal: 'lcdif_data, 22', pin_signal: GPIO_DISP_B2_14, pull_up_down_config: Pull_Up, drive_strength: Normal}
  - {pin_num: D11, peripheral: LCDIF, signal: lcdif_hsync, pin_signal: GPIO_DISP_B1_02, pdrv_config: Normal_Driver}
  - {pin_num: E11, peripheral: LCDIF, signal: lcdif_vsync, pin_signal: GPIO_DISP_B1_03, pdrv_config: Normal_Driver}
  - {pin_num: D13, peripheral: LCDIF, signal: lcdif_enable, pin_signal: GPIO_DISP_B1_01, pdrv_config: Normal_Driver}
  - {pin_num: A4, peripheral: LCDIF, signal: 'lcdif_data, 23', pin_signal: GPIO_DISP_B2_15, drive_strength: Normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLcdifPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLcdifPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_00_VIDEO_MUX_LCDIF_CLK,  /* GPIO_DISP_B1_00 is configured as VIDEO_MUX_LCDIF_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_01_VIDEO_MUX_LCDIF_ENABLE,  /* GPIO_DISP_B1_01 is configured as VIDEO_MUX_LCDIF_ENABLE */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_02_VIDEO_MUX_LCDIF_HSYNC,  /* GPIO_DISP_B1_02 is configured as VIDEO_MUX_LCDIF_HSYNC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_03_VIDEO_MUX_LCDIF_VSYNC,  /* GPIO_DISP_B1_03 is configured as VIDEO_MUX_LCDIF_VSYNC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_04_VIDEO_MUX_LCDIF_DATA00,  /* GPIO_DISP_B1_04 is configured as VIDEO_MUX_LCDIF_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_05_VIDEO_MUX_LCDIF_DATA01,  /* GPIO_DISP_B1_05 is configured as VIDEO_MUX_LCDIF_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_06_VIDEO_MUX_LCDIF_DATA02,  /* GPIO_DISP_B1_06 is configured as VIDEO_MUX_LCDIF_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_07_VIDEO_MUX_LCDIF_DATA03,  /* GPIO_DISP_B1_07 is configured as VIDEO_MUX_LCDIF_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_08_VIDEO_MUX_LCDIF_DATA04,  /* GPIO_DISP_B1_08 is configured as VIDEO_MUX_LCDIF_DATA04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_09_VIDEO_MUX_LCDIF_DATA05,  /* GPIO_DISP_B1_09 is configured as VIDEO_MUX_LCDIF_DATA05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_10_VIDEO_MUX_LCDIF_DATA06,  /* GPIO_DISP_B1_10 is configured as VIDEO_MUX_LCDIF_DATA06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B1_11_VIDEO_MUX_LCDIF_DATA07,  /* GPIO_DISP_B1_11 is configured as VIDEO_MUX_LCDIF_DATA07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_00_VIDEO_MUX_LCDIF_DATA08,  /* GPIO_DISP_B2_00 is configured as VIDEO_MUX_LCDIF_DATA08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_01_VIDEO_MUX_LCDIF_DATA09,  /* GPIO_DISP_B2_01 is configured as VIDEO_MUX_LCDIF_DATA09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_02_VIDEO_MUX_LCDIF_DATA10,  /* GPIO_DISP_B2_02 is configured as VIDEO_MUX_LCDIF_DATA10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_03_VIDEO_MUX_LCDIF_DATA11,  /* GPIO_DISP_B2_03 is configured as VIDEO_MUX_LCDIF_DATA11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_04_VIDEO_MUX_LCDIF_DATA12,  /* GPIO_DISP_B2_04 is configured as VIDEO_MUX_LCDIF_DATA12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_05_VIDEO_MUX_LCDIF_DATA13,  /* GPIO_DISP_B2_05 is configured as VIDEO_MUX_LCDIF_DATA13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_06_VIDEO_MUX_LCDIF_DATA14,  /* GPIO_DISP_B2_06 is configured as VIDEO_MUX_LCDIF_DATA14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_07_VIDEO_MUX_LCDIF_DATA15,  /* GPIO_DISP_B2_07 is configured as VIDEO_MUX_LCDIF_DATA15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_08_VIDEO_MUX_LCDIF_DATA16,  /* GPIO_DISP_B2_08 is configured as VIDEO_MUX_LCDIF_DATA16 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_09_VIDEO_MUX_LCDIF_DATA17,  /* GPIO_DISP_B2_09 is configured as VIDEO_MUX_LCDIF_DATA17 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_10_VIDEO_MUX_LCDIF_DATA18,  /* GPIO_DISP_B2_10 is configured as VIDEO_MUX_LCDIF_DATA18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_11_VIDEO_MUX_LCDIF_DATA19,  /* GPIO_DISP_B2_11 is configured as VIDEO_MUX_LCDIF_DATA19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_12_VIDEO_MUX_LCDIF_DATA20,  /* GPIO_DISP_B2_12 is configured as VIDEO_MUX_LCDIF_DATA20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_13_VIDEO_MUX_LCDIF_DATA21,  /* GPIO_DISP_B2_13 is configured as VIDEO_MUX_LCDIF_DATA21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_14_VIDEO_MUX_LCDIF_DATA22,  /* GPIO_DISP_B2_14 is configured as VIDEO_MUX_LCDIF_DATA22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_15_VIDEO_MUX_LCDIF_DATA23,  /* GPIO_DISP_B2_15 is configured as VIDEO_MUX_LCDIF_DATA23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_00_VIDEO_MUX_LCDIF_CLK,  /* GPIO_DISP_B1_00 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_01_VIDEO_MUX_LCDIF_ENABLE,  /* GPIO_DISP_B1_01 PAD functional properties : */
      0x0AU);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PD
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_02_VIDEO_MUX_LCDIF_HSYNC,  /* GPIO_DISP_B1_02 PAD functional properties : */
      0x0AU);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PD
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_03_VIDEO_MUX_LCDIF_VSYNC,  /* GPIO_DISP_B1_03 PAD functional properties : */
      0x0AU);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PD
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_04_VIDEO_MUX_LCDIF_DATA00,  /* GPIO_DISP_B1_04 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_05_VIDEO_MUX_LCDIF_DATA01,  /* GPIO_DISP_B1_05 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_06_VIDEO_MUX_LCDIF_DATA02,  /* GPIO_DISP_B1_06 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_07_VIDEO_MUX_LCDIF_DATA03,  /* GPIO_DISP_B1_07 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_08_VIDEO_MUX_LCDIF_DATA04,  /* GPIO_DISP_B1_08 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_09_VIDEO_MUX_LCDIF_DATA05,  /* GPIO_DISP_B1_09 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_10_VIDEO_MUX_LCDIF_DATA06,  /* GPIO_DISP_B1_10 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B1_11_VIDEO_MUX_LCDIF_DATA07,  /* GPIO_DISP_B1_11 PAD functional properties : */
      0x06U);                                 /* PDRV Field: normal driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_00_VIDEO_MUX_LCDIF_DATA08,  /* GPIO_DISP_B2_00 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_01_VIDEO_MUX_LCDIF_DATA09,  /* GPIO_DISP_B2_01 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_02_VIDEO_MUX_LCDIF_DATA10,  /* GPIO_DISP_B2_02 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_03_VIDEO_MUX_LCDIF_DATA11,  /* GPIO_DISP_B2_03 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_04_VIDEO_MUX_LCDIF_DATA12,  /* GPIO_DISP_B2_04 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_05_VIDEO_MUX_LCDIF_DATA13,  /* GPIO_DISP_B2_05 PAD functional properties : */
      0x08U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_06_VIDEO_MUX_LCDIF_DATA14,  /* GPIO_DISP_B2_06 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_07_VIDEO_MUX_LCDIF_DATA15,  /* GPIO_DISP_B2_07 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_08_VIDEO_MUX_LCDIF_DATA16,  /* GPIO_DISP_B2_08 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_09_VIDEO_MUX_LCDIF_DATA17,  /* GPIO_DISP_B2_09 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_10_VIDEO_MUX_LCDIF_DATA18,  /* GPIO_DISP_B2_10 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_11_VIDEO_MUX_LCDIF_DATA19,  /* GPIO_DISP_B2_11 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_12_VIDEO_MUX_LCDIF_DATA20,  /* GPIO_DISP_B2_12 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_13_VIDEO_MUX_LCDIF_DATA21,  /* GPIO_DISP_B2_13 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_14_VIDEO_MUX_LCDIF_DATA22,  /* GPIO_DISP_B2_14 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_15_VIDEO_MUX_LCDIF_DATA23,  /* GPIO_DISP_B2_15 PAD functional properties : */
      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
