/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 2.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.1.0.2188
*
********************************************************************************
* Copyright 2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                                         0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                                     0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                                      0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                                      0x1801
#define __UUID_SERVICE_MOTOCONSDK                                             0x7Au, 0x15u, 0xC0u, 0x28u, 0xA4u, 0x9Du, 0xEAu, 0xA5u, 0xA7u, 0x46u, 0xCFu, 0xECu, 0xF4u, 0xCDu, 0xA2u, 0xAFu
#define __UUID_CHARACTERISTIC_MOTOCONSDK_WRITE                                0xEBu, 0xA8u, 0x54u, 0x00u, 0x92u, 0x2Au, 0x13u, 0xB3u, 0x75u, 0x4Eu, 0xA1u, 0xE5u, 0xF9u, 0xC7u, 0x06u, 0xB6u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_NOTIFY                               0x6Cu, 0x06u, 0xA3u, 0x1Bu, 0x5Au, 0x75u, 0x1Cu, 0x8Cu, 0x06u, 0x43u, 0x05u, 0xB6u, 0x26u, 0x0Du, 0x81u, 0x9Cu
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION                 0x2902
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_VEHICLE_STATUS                0xD1u, 0x00u, 0x26u, 0xA1u, 0x85u, 0x6Fu, 0x9Cu, 0xBAu, 0x61u, 0x4Fu, 0xF6u, 0x87u, 0x88u, 0x27u, 0xABu, 0x75u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_VEHICLE_CONTROL               0x4Au, 0xF7u, 0x20u, 0x65u, 0x77u, 0xD1u, 0xDFu, 0xA5u, 0x6Au, 0x4Fu, 0x90u, 0xA0u, 0x26u, 0x18u, 0x85u, 0x56u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_VEHICLE_DATA                  0x84u, 0x44u, 0xA4u, 0xC1u, 0x17u, 0x20u, 0xAAu, 0x83u, 0x63u, 0x40u, 0x8Fu, 0xEAu, 0xABu, 0xAEu, 0x98u, 0xE9u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_PHONE_STATUS                  0x68u, 0x30u, 0x45u, 0x58u, 0x30u, 0x84u, 0x84u, 0xB0u, 0xA1u, 0x42u, 0x72u, 0x3Du, 0x79u, 0x7Au, 0x1Au, 0x1Au
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_PHONE_CONTROL                 0x6Au, 0xD1u, 0xA3u, 0x4Au, 0xB4u, 0x3Au, 0xEDu, 0x83u, 0x6Bu, 0x4Fu, 0x2Fu, 0xE4u, 0x51u, 0x84u, 0x80u, 0x77u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_TO_PHONE_DATA                    0x7Au, 0xE2u, 0x72u, 0x36u, 0xBEu, 0x62u, 0x98u, 0xBDu, 0xD5u, 0x4Du, 0x88u, 0xA5u, 0xEEu, 0x56u, 0x74u, 0x34u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_STATUS       0xF6u, 0x4Du, 0x3Eu, 0x31u, 0xA7u, 0xB5u, 0x60u, 0x8Bu, 0xFCu, 0x4Eu, 0x3Cu, 0x0Eu, 0xD9u, 0xE5u, 0x36u, 0x7Du
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_CONTROL      0xF9u, 0x7Fu, 0x86u, 0xBDu, 0xA1u, 0x0Eu, 0x34u, 0x99u, 0x9Eu, 0x48u, 0x29u, 0xE8u, 0xCAu, 0x92u, 0x85u, 0x59u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_DATA         0x86u, 0x4Eu, 0x88u, 0xAEu, 0x5Cu, 0xA7u, 0x83u, 0xB7u, 0x09u, 0x42u, 0x5Fu, 0xCCu, 0xE5u, 0x50u, 0x5Bu, 0x2Au
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_CAN_STATUS                       0xC6u, 0x89u, 0xDDu, 0xEEu, 0x5Fu, 0xF5u, 0x34u, 0xABu, 0x92u, 0x41u, 0xDAu, 0x3Bu, 0xAFu, 0x65u, 0x64u, 0x2Fu
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_CAN_CONTROL                      0x7Au, 0x03u, 0x5Fu, 0xEBu, 0x35u, 0xACu, 0x0Fu, 0xADu, 0xFDu, 0x40u, 0x84u, 0x0Cu, 0x61u, 0x71u, 0x82u, 0xD1u
#define __UUID_CHARACTERISTIC_MOTOCONSDK_DDT_CAN_DATA                         0xEAu, 0xCDu, 0x97u, 0x9Cu, 0xE6u, 0xB3u, 0x20u, 0xB3u, 0xBCu, 0x40u, 0xA7u, 0x51u, 0x82u, 0x3Bu, 0x52u, 0xCFu

/* Service Generic Access */
#define HDLS_GAP                                                              0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                                  0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                                            0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                                   0x04
#define HDLC_GAP_APPEARANCE_VALUE                                             0x05

/* Service Generic Attribute */
#define HDLS_GATT                                                             0x06

/* Service MotoconSDK */
#define HDLS_MOTOCONSDK                                                       0x07
/* Characteristic WRITE */
#define HDLC_MOTOCONSDK_WRITE                                                 0x08
#define HDLC_MOTOCONSDK_WRITE_VALUE                                           0x09
/* Characteristic NOTIFY */
#define HDLC_MOTOCONSDK_NOTIFY                                                0x0A
#define HDLC_MOTOCONSDK_NOTIFY_VALUE                                          0x0B
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_NOTIFY_CLIENT_CHAR_CONFIG                             0x0C
/* Characteristic DDT TO VEHICLE STATUS */
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_STATUS                                 0x0D
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_STATUS_VALUE                           0x0E
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_TO_VEHICLE_STATUS_CLIENT_CHAR_CONFIG              0x0F
/* Characteristic DDT TO VEHICLE CONTROL */
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_CONTROL                                0x10
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_CONTROL_VALUE                          0x11
/* Characteristic DDT TO VEHICLE DATA */
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_DATA                                   0x12
#define HDLC_MOTOCONSDK_DDT_TO_VEHICLE_DATA_VALUE                             0x13
/* Characteristic DDT TO PHONE STATUS */
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_STATUS                                   0x14
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_STATUS_VALUE                             0x15
/* Characteristic DDT TO PHONE CONTROL */
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_CONTROL                                  0x16
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_CONTROL_VALUE                            0x17
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_TO_PHONE_CONTROL_CLIENT_CHAR_CONFIG               0x18
/* Characteristic DDT TO PHONE DATA */
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_DATA                                     0x19
#define HDLC_MOTOCONSDK_DDT_TO_PHONE_DATA_VALUE                               0x1A
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_TO_PHONE_DATA_CLIENT_CHAR_CONFIG                  0x1B
/* Characteristic DDT VEHICLE INFORMATION STATUS */
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_STATUS                        0x1C
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_STATUS_VALUE                  0x1D
/* Characteristic DDT VEHICLE INFORMATION CONTROL */
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_CONTROL                       0x1E
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_CONTROL_VALUE                 0x1F
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_VEHICLE_INFORMATION_CONTROL_CLIENT_CHAR_CONFIG    0x20
/* Characteristic DDT VEHICLE INFORMATION DATA */
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_DATA                          0x21
#define HDLC_MOTOCONSDK_DDT_VEHICLE_INFORMATION_DATA_VALUE                    0x22
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_VEHICLE_INFORMATION_DATA_CLIENT_CHAR_CONFIG       0x23
/* Characteristic DDT CAN STATUS */
#define HDLC_MOTOCONSDK_DDT_CAN_STATUS                                        0x24
#define HDLC_MOTOCONSDK_DDT_CAN_STATUS_VALUE                                  0x25
/* Characteristic DDT CAN CONTROL */
#define HDLC_MOTOCONSDK_DDT_CAN_CONTROL                                       0x26
#define HDLC_MOTOCONSDK_DDT_CAN_CONTROL_VALUE                                 0x27
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_CAN_CONTROL_CLIENT_CHAR_CONFIG                    0x28
/* Characteristic DDT CAN DATA */
#define HDLC_MOTOCONSDK_DDT_CAN_DATA                                          0x29
#define HDLC_MOTOCONSDK_DDT_CAN_DATA_VALUE                                    0x2A
/* Descriptor Client Characteristic Configuration */
#define HDLD_MOTOCONSDK_DDT_CAN_DATA_CLIENT_CHAR_CONFIG                       0x2B

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_motoconsdk_write[];
extern const uint16_t app_motoconsdk_write_len;
extern uint8_t app_motoconsdk_notify[];
extern const uint16_t app_motoconsdk_notify_len;
extern uint8_t app_motoconsdk_notify_client_char_config[];
extern const uint16_t app_motoconsdk_notify_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_to_vehicle_status[];
extern const uint16_t app_motoconsdk_ddt_to_vehicle_status_len;
extern uint8_t app_motoconsdk_ddt_to_vehicle_status_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_to_vehicle_status_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_to_vehicle_control[];
extern const uint16_t app_motoconsdk_ddt_to_vehicle_control_len;
extern uint8_t app_motoconsdk_ddt_to_vehicle_data[];
extern const uint16_t app_motoconsdk_ddt_to_vehicle_data_len;
extern uint8_t app_motoconsdk_ddt_to_phone_status[];
extern const uint16_t app_motoconsdk_ddt_to_phone_status_len;
extern uint8_t app_motoconsdk_ddt_to_phone_control[];
extern const uint16_t app_motoconsdk_ddt_to_phone_control_len;
extern uint8_t app_motoconsdk_ddt_to_phone_control_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_to_phone_control_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_to_phone_data[];
extern const uint16_t app_motoconsdk_ddt_to_phone_data_len;
extern uint8_t app_motoconsdk_ddt_to_phone_data_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_to_phone_data_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_vehicle_information_status[];
extern const uint16_t app_motoconsdk_ddt_vehicle_information_status_len;
extern uint8_t app_motoconsdk_ddt_vehicle_information_control[];
extern const uint16_t app_motoconsdk_ddt_vehicle_information_control_len;
extern uint8_t app_motoconsdk_ddt_vehicle_information_control_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_vehicle_information_control_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_vehicle_information_data[];
extern const uint16_t app_motoconsdk_ddt_vehicle_information_data_len;
extern uint8_t app_motoconsdk_ddt_vehicle_information_data_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_vehicle_information_data_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_can_status[];
extern const uint16_t app_motoconsdk_ddt_can_status_len;
extern uint8_t app_motoconsdk_ddt_can_control[];
extern const uint16_t app_motoconsdk_ddt_can_control_len;
extern uint8_t app_motoconsdk_ddt_can_control_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_can_control_client_char_config_len;
extern uint8_t app_motoconsdk_ddt_can_data[];
extern const uint16_t app_motoconsdk_ddt_can_data_len;
extern uint8_t app_motoconsdk_ddt_can_data_client_char_config[];
extern const uint16_t app_motoconsdk_ddt_can_data_client_char_config_len;

#endif /* CYCFG_GATT_DB_H */

